package VISTA;

import javax.swing.ButtonGroup;
import javax.swing.JComboBox;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

public class Formulario extends javax.swing.JFrame {

    public Formulario() {
        initComponents();
        inicializarTabla();
        setLocationRelativeTo(null);
    }
    private void inicializarTabla() {
    String[] columnas = {"Cedula","Nombre", "Curso", "Carrera", "Sexo","Correo"};
    DefaultTableModel modelo = new DefaultTableModel(null, columnas);
    TableReportes.setModel(modelo);
    TablaEliminar1.setModel(modelo);
}
    public JTable getTableReportes() {
    return TableReportes;
}
    public JTextField getTxtNombre() {
    return txtNombre;
}

public JTextField getTxtCurso() {
    return txtCurso;
}
public JTextField getTxtCedula(){
    return txtCedula;
}
public JTextField getTxtCorreo() {
    return txtCorreo;
}
public JComboBox<String> getComboBoxCarrera() {
    return ComboBoxCarrera;
}

public ButtonGroup getGrupoSexo() {
    return btnGrupo1;
}

public String getSelectedSexo() {
    if (RadioButtonMasculino.isSelected()) return "Masculino";
    if (RadioButtonFemenino.isSelected()) return "Femenino";
    return "No seleccionado";
}

public JTabbedPane getTabPanel() {
    return jTabbedPanel;  // Asegúrate que el nombre coincida
}
//Getter y Setters para Editar y eliminar
public JTextField getTxtBuscar1() {
    return txtBuscar1;
}

public JTextField getTxtNombre1() {
    return txtNombre1;
}

public JTextField getTxtCurso1() {
    return txtCurso1;
}

public JTextField getTxtCorreo1() {
    return txtCorreo1;
}

public JComboBox<String> getComboBoxCarrera1() {
    return ComboBoxCarrera1;
}

public javax.swing.JButton getBtnBuscar() {
    return btnBuscar;
}

public javax.swing.JButton getBtnEditar() {
    return btnEditar;
}

public javax.swing.JButton getBtnEliminar() {
    return btnEliminar;
}

public ButtonGroup getBtnGrupo2() {
    return btnGrupo2;
}

// Sexo seleccionado en edición
public String getSelectedSexo1() {
    if (jRadioButtonMasculino1.isSelected()) return "Masculino";
    if (jRadioButtonFemenino1.isSelected()) return "Femenino";
    return "No seleccionado";
}

// Establecer el sexo en los radio buttons
public void setSelectedSexo1(String sexo) {
    if (sexo.equalsIgnoreCase("Masculino")) {
        jRadioButtonMasculino1.setSelected(true);
    } else if (sexo.equalsIgnoreCase("Femenino")) {
        jRadioButtonFemenino1.setSelected(true);
    } else {
        btnGrupo2.clearSelection();
    }
}
public void limpiarCamposEditar() {
    txtBuscar1.setText("");
    txtNombre1.setText("");
    txtCurso1.setText("");
    ComboBoxCarrera1.setSelectedIndex(0);
    txtCorreo1.setText("");
    btnGrupo2.clearSelection(); // Limpia los radio buttons del sexo en edición
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupo1 = new javax.swing.ButtonGroup();
        btnGrupo2 = new javax.swing.ButtonGroup();
        jTabbedPanel = new javax.swing.JTabbedPane();
        PanelAlumno = new javax.swing.JPanel();
        lblnombre = new javax.swing.JLabel();
        lblCurso = new javax.swing.JLabel();
        lblCarrera = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCurso = new javax.swing.JTextField();
        ComboBoxCarrera = new javax.swing.JComboBox<>();
        lblsexo = new javax.swing.JLabel();
        RadioButtonMasculino = new javax.swing.JRadioButton();
        RadioButtonFemenino = new javax.swing.JRadioButton();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblcedula = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        PanelReportes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableReportes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        PanelEditar = new javax.swing.JPanel();
        txtBuscar1 = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        txtNombre1 = new javax.swing.JTextField();
        lblnombre1 = new javax.swing.JLabel();
        lblcurso1 = new javax.swing.JLabel();
        txtCurso1 = new javax.swing.JTextField();
        lblcorreo1 = new javax.swing.JLabel();
        txtCorreo1 = new javax.swing.JTextField();
        lblcarrera1 = new javax.swing.JLabel();
        ComboBoxCarrera1 = new javax.swing.JComboBox<>();
        lblsexo1 = new javax.swing.JLabel();
        jRadioButtonMasculino1 = new javax.swing.JRadioButton();
        jRadioButtonFemenino1 = new javax.swing.JRadioButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaEliminar1 = new javax.swing.JTable();
        lblbuscar1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelAlumno.setBackground(new java.awt.Color(0, 204, 204));

        lblnombre.setText("Nombre:");

        lblCurso.setText("Curso:");

        lblCarrera.setText("Carrera:");

        ComboBoxCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción", "Desarollo Software", "Big Data", "Cyberseguridad", "Mecatronica", "Tributacion", "Produccion Audiovisual", "Entrenamiento Deportivo" }));

        lblsexo.setText("Sexo:");

        btnGrupo1.add(RadioButtonMasculino);
        RadioButtonMasculino.setText("Masculino");

        btnGrupo1.add(RadioButtonFemenino);
        RadioButtonFemenino.setText("Femenino");

        btnGuardar.setText("Guardar");

        btnSalir.setText("Salir");

        lblcedula.setText("Cedula:");

        jLabel2.setText("Correo:");

        javax.swing.GroupLayout PanelAlumnoLayout = new javax.swing.GroupLayout(PanelAlumno);
        PanelAlumno.setLayout(PanelAlumnoLayout);
        PanelAlumnoLayout.setHorizontalGroup(
            PanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAlumnoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(PanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAlumnoLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 633, Short.MAX_VALUE)
                        .addComponent(btnSalir)
                        .addGap(118, 118, 118))
                    .addGroup(PanelAlumnoLayout.createSequentialGroup()
                        .addGroup(PanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(PanelAlumnoLayout.createSequentialGroup()
                                    .addGroup(PanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblCarrera)
                                        .addComponent(lblsexo))
                                    .addGap(36, 36, 36))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAlumnoLayout.createSequentialGroup()
                                    .addComponent(lblCurso)
                                    .addGap(52, 52, 52)))
                            .addGroup(PanelAlumnoLayout.createSequentialGroup()
                                .addGroup(PanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblnombre)
                                    .addComponent(lblcedula))
                                .addGap(39, 39, 39)))
                        .addGroup(PanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboBoxCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelAlumnoLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(PanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RadioButtonMasculino)
                                    .addComponent(RadioButtonFemenino)))
                            .addGroup(PanelAlumnoLayout.createSequentialGroup()
                                .addGroup(PanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtCurso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCedula, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(34, 34, 34)
                                .addComponent(jLabel2)
                                .addGap(30, 30, 30)
                                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(403, Short.MAX_VALUE))))
        );
        PanelAlumnoLayout.setVerticalGroup(
            PanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAlumnoLayout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(PanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcedula)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblnombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCurso))
                .addGap(18, 18, 18)
                .addGroup(PanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCarrera))
                .addGap(18, 18, 18)
                .addGroup(PanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAlumnoLayout.createSequentialGroup()
                        .addComponent(RadioButtonMasculino)
                        .addGap(18, 18, 18)
                        .addComponent(RadioButtonFemenino)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAlumnoLayout.createSequentialGroup()
                        .addComponent(lblsexo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)))
                .addGroup(PanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnSalir))
                .addGap(24, 24, 24))
        );

        jTabbedPanel.addTab("Alumno", PanelAlumno);

        PanelReportes.setBackground(new java.awt.Color(0, 204, 204));

        TableReportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TableReportes);

        jLabel1.setText("Estudiantes Registrados");

        javax.swing.GroupLayout PanelReportesLayout = new javax.swing.GroupLayout(PanelReportes);
        PanelReportes.setLayout(PanelReportesLayout);
        PanelReportesLayout.setHorizontalGroup(
            PanelReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelReportesLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(PanelReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 892, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
        PanelReportesLayout.setVerticalGroup(
            PanelReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelReportesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jTabbedPanel.addTab("Reportes", PanelReportes);

        PanelEditar.setBackground(new java.awt.Color(0, 204, 204));

        txtBuscar1.setToolTipText("Ingrese el numero de Cedula");

        btnBuscar.setText("Buscar");
        btnBuscar.setToolTipText("Ingrese el numero de Cedula");

        lblnombre1.setText("Nombre:");

        lblcurso1.setText("Curso:");

        lblcorreo1.setText("Correo:");

        lblcarrera1.setText("Carrera:");

        ComboBoxCarrera1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desarollo Software", "Big Data", "Cyberseguridad", "Mecatronica", "Tributacion", "Produccion Audiovisual", "Entrenamiento Deportivo" }));

        lblsexo1.setText("Sexo:");

        btnGrupo2.add(jRadioButtonMasculino1);
        jRadioButtonMasculino1.setText("Masculino");

        btnGrupo2.add(jRadioButtonFemenino1);
        jRadioButtonFemenino1.setText("Femenino");

        btnEditar.setText("Editar");

        btnEliminar.setText("Eliminar");

        TablaEliminar1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TablaEliminar1);

        lblbuscar1.setText("Ingrese el numero de Cedula");

        javax.swing.GroupLayout PanelEditarLayout = new javax.swing.GroupLayout(PanelEditar);
        PanelEditar.setLayout(PanelEditarLayout);
        PanelEditarLayout.setHorizontalGroup(
            PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelEditarLayout.createSequentialGroup()
                        .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelEditarLayout.createSequentialGroup()
                                .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelEditarLayout.createSequentialGroup()
                                        .addComponent(txtBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnBuscar))
                                    .addComponent(btnEliminar))
                                .addGap(76, 76, 76)
                                .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblnombre1)
                                    .addComponent(lblcurso1)
                                    .addComponent(lblsexo1)))
                            .addGroup(PanelEditarLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(lblbuscar1)))
                        .addGap(33, 33, 33)
                        .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelEditarLayout.createSequentialGroup()
                                .addComponent(jRadioButtonMasculino1)
                                .addGap(26, 26, 26)
                                .addComponent(jRadioButtonFemenino1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(PanelEditarLayout.createSequentialGroup()
                                .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCurso1, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                    .addComponent(txtNombre1))
                                .addGap(84, 84, 84)
                                .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelEditarLayout.createSequentialGroup()
                                        .addComponent(lblcorreo1)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCorreo1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelEditarLayout.createSequentialGroup()
                                        .addComponent(lblcarrera1)
                                        .addGap(18, 18, 18)
                                        .addComponent(ComboBoxCarrera1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(95, 95, 95))))
                    .addGroup(PanelEditarLayout.createSequentialGroup()
                        .addComponent(btnEditar)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(PanelEditarLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelEditarLayout.setVerticalGroup(
            PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEditarLayout.createSequentialGroup()
                .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelEditarLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblnombre1)
                            .addComponent(lblcorreo1)
                            .addComponent(txtCorreo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblcurso1)
                            .addComponent(txtCurso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblcarrera1)
                            .addComponent(ComboBoxCarrera1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelEditarLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblbuscar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar))))
                .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelEditarLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblsexo1)
                            .addGroup(PanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jRadioButtonMasculino1)
                                .addComponent(jRadioButtonFemenino1))))
                    .addGroup(PanelEditarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jTabbedPanel.addTab("Editar", PanelEditar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPanel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jTabbedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> ComboBoxCarrera;
    public javax.swing.JComboBox<String> ComboBoxCarrera1;
    private javax.swing.JPanel PanelAlumno;
    private javax.swing.JPanel PanelEditar;
    private javax.swing.JPanel PanelReportes;
    private javax.swing.JRadioButton RadioButtonFemenino;
    public javax.swing.JRadioButton RadioButtonMasculino;
    private javax.swing.JTable TablaEliminar1;
    public javax.swing.JTable TableReportes;
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnEditar;
    public javax.swing.JButton btnEliminar;
    public javax.swing.ButtonGroup btnGrupo1;
    private javax.swing.ButtonGroup btnGrupo2;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JRadioButton jRadioButtonFemenino1;
    public javax.swing.JRadioButton jRadioButtonMasculino1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPanel;
    private javax.swing.JLabel lblCarrera;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblbuscar1;
    private javax.swing.JLabel lblcarrera1;
    private javax.swing.JLabel lblcedula;
    private javax.swing.JLabel lblcorreo1;
    private javax.swing.JLabel lblcurso1;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblnombre1;
    private javax.swing.JLabel lblsexo;
    private javax.swing.JLabel lblsexo1;
    public javax.swing.JTextField txtBuscar1;
    public javax.swing.JTextField txtCedula;
    public javax.swing.JTextField txtCorreo;
    public javax.swing.JTextField txtCorreo1;
    public javax.swing.JTextField txtCurso;
    public javax.swing.JTextField txtCurso1;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtNombre1;
    // End of variables declaration//GEN-END:variables
}
